repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.5'
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  - repo: local
    hooks:
      - id: black
        name: black
        language: python
        pass_filenames: true
        entry: black --preview
        types: [file, python]
 
